### ISSUE TITLE
Getting  \n\n\r\177 INCORRECT when trying to login with valid Tacacs user

### ISSUE THREAD

**Issue by stevetavve** [stemid/tacacs#1]
I followed all of the instructions but I am getting an incorrect password when attempting to login with a valid Tacas user.

Below I captured everything I could to show my environment. Any help is greatly appreciated.

Wireshark is showing this 

Password Length 13
Password: \b\n\r\177INCORRECT

```
[root@localhost ~]# ls -alR /usr/local/lib
/usr/local/lib:
total 248
drwxr-xr-x.  4 root root   4096 Mar 30 11:22 .
drwxr-xr-x. 12 root root   4096 Mar 30 06:46 ..
lrwxrwxrwx   1 root root     23 Mar 30 11:20 libnss_tacplus.so -> libnss_tacplus.so.2.0.0
lrwxrwxrwx   1 root root     23 Mar 30 11:20 libnss_tacplus.so.2 -> libnss_tacplus.so.2.0.0
-rwxr-xr-x   1 root root  15457 Mar 30 11:20 libnss_tacplus.so.2.0.0
lrwxrwxrwx   1 root root     26 Mar 30 11:22 libsimple_tacacct.so.1 -> libsimple_tacacct.so.1.0.0
-rwxr-xr-x   1 root root  25265 Mar 30 11:22 libsimple_tacacct.so.1.0.0
lrwxrwxrwx   1 root root     23 Mar 30 11:14 libtacplus_map.so -> libtacplus_map.so.1.0.0
lrwxrwxrwx   1 root root     23 Mar 30 11:14 libtacplus_map.so.1 -> libtacplus_map.so.1.0.0
-rwxr-xr-x   1 root root  45634 Mar 30 11:14 libtacplus_map.so.1.0.0
lrwxrwxrwx   1 root root     15 Mar 30 11:14 libtac.so -> libtac.so.2.0.0
lrwxrwxrwx   1 root root     15 Mar 30 11:14 libtac.so.2 -> libtac.so.2.0.0
-rwxr-xr-x   1 root root 140939 Mar 30 11:14 libtac.so.2.0.0
drwxr-xr-x   2 root root   4096 Mar 30 11:14 pkgconfig
drwxr-xr-x   2 root root   4096 Mar 30 11:14 security

/usr/local/lib/pkgconfig:
total 12
drwxr-xr-x  2 root root 4096 Mar 30 11:14 .
drwxr-xr-x. 4 root root 4096 Mar 30 11:22 ..
-rw-r--r--  1 root root  275 Mar 30 11:14 libtac.pc

/usr/local/lib/security:
total 92
drwxr-xr-x  2 root root  4096 Mar 30 11:14 .
drwxr-xr-x. 4 root root  4096 Mar 30 11:22 ..
-rwxr-xr-x  1 root root 84363 Mar 30 11:14 pam_tacplus.so

```

```
[root@localhost ~]# cat /var/log/debug.log 
Mar 30 13:18:00 localhost sshd[2417]: Invalid user tacacsAdmin from 10.254.1.180
Mar 30 13:18:00 localhost sshd[2417]: input_userauth_request: invalid user tacacsAdmin [preauth]
Mar 30 13:18:02 localhost PAM-tacplus[2417]: auth failed: 2
Mar 30 13:18:02 localhost sshd[2417]: pam_unix(sshd:auth): check pass; user unknown
Mar 30 13:18:02 localhost sshd[2417]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=tron.tavve.com
Mar 30 13:18:05 localhost sshd[2417]: Failed password for invalid user tacacsAdmin from 10.254.1.180 port 44406 ssh2
Mar 30 13:20:01 localhost systemd: Started Session 4 of user root.
Mar 30 13:20:01 localhost systemd: Starting Session 4 of user root.
Mar 30 13:20:01 localhost CROND[2420]: (root) CMD (/usr/lib64/sa/sa1 1 1)

```

`[root@localhost ~]# cat /etc/ld.so.conf.d/tacacs.conf
/usr/local/lib
/usr/local/lib/security
`

`[root@localhost ~]# cat /etc/nsswitch.conf 
#
# /etc/nsswitch.conf
#
# An example Name Service Switch config file. This file should be
# sorted with the most-used services at the beginning.
#
# The entry '[NOTFOUND=return]' means that the search for an
# entry should stop if the search in the previous entry turned
# up nothing. Note that if the search failed due to some other reason
# (like no NIS server responding) then the search continues with the
# next entry.
#
# Valid entries include:
#
#       nisplus                 Use NIS+ (NIS version 3)
#       nis                     Use NIS (NIS version 2), also called YP
#       dns                     Use DNS (Domain Name Service)
#       files                   Use the local files
#       db                      Use the local database (.db) files
#       compat                  Use NIS on compat mode
#       hesiod                  Use Hesiod for user lookups
#       [NOTFOUND=return]       Stop searching if not found so far
#

# To use db, put the "db" in front of "files" for entries you want to be
# looked up first in the databases
#
# Example:
#passwd:    db files nisplus nis
#shadow:    db files nisplus nis
#group:     db files nisplus nis

passwd:     tacplus files 
shadow:     files
group:      files
#initgroups: files

#hosts:     db files nisplus nis dns
hosts:      files dns

# Example - obey only what nisplus tells us...
#services:   nisplus [NOTFOUND=return] files
#networks:   nisplus [NOTFOUND=return] files
#protocols:  nisplus [NOTFOUND=return] files
#rpc:        nisplus [NOTFOUND=return] files
#ethers:     nisplus [NOTFOUND=return] files
#netmasks:   nisplus [NOTFOUND=return] files     

bootparams: nisplus [NOTFOUND=return] files

ethers:     files
netmasks:   files
networks:   files
protocols:  files
rpc:        files
services:   files sss

netgroup:   files sss

publickey:  nisplus

automount:  files
aliases:    files nisplus
`

`[root@localhost ~]# ls -l /home
total 64
drwx------ 2 tacacs0  tacacs0  4096 Mar 30 13:11 tacacs0
drwx------ 2 tacacs1  tacacs1  4096 Mar 30 13:11 tacacs1
drwx------ 2 tacacs10 tacacs10 4096 Mar 30 13:11 tacacs10
drwx------ 2 tacacs11 tacacs11 4096 Mar 30 13:11 tacacs11
drwx------ 2 tacacs12 tacacs12 4096 Mar 30 13:11 tacacs12
drwx------ 2 tacacs13 tacacs13 4096 Mar 30 13:11 tacacs13
drwx------ 2 tacacs14 tacacs14 4096 Mar 30 13:12 tacacs14
drwx------ 2 tacacs15 tacacs15 4096 Mar 30 13:12 tacacs15
drwx------ 2 tacacs2  tacacs2  4096 Mar 30 13:11 tacacs2
drwx------ 2 tacacs3  tacacs3  4096 Mar 30 13:11 tacacs3
drwx------ 2 tacacs4  tacacs4  4096 Mar 30 13:11 tacacs4
drwx------ 2 tacacs5  tacacs5  4096 Mar 30 13:11 tacacs5
drwx------ 2 tacacs6  tacacs6  4096 Mar 30 13:11 tacacs6
drwx------ 2 tacacs7  tacacs7  4096 Mar 30 13:11 tacacs7
drwx------ 2 tacacs8  tacacs8  4096 Mar 30 13:11 tacacs8
drwx------ 2 tacacs9  tacacs9  4096 Mar 30 13:11 tacacs9
`

`[root@localhost ~]# cat /etc/tacplus_servers
# This is a common file used by audisp-tacplus, libpam_tacplus, and
# libtacplus_map config files as shipped.
#
# Any tac_plus client config can go here that is common to all users of this
# file, but typically it's just the TACACS+ server IP address(es) and shared
# secret(s)

secret=andy
server=10.254.1.117
`

`[root@localhost ~]# cat /etc/tacplus_nss.conf
#%NSS_TACPLUS-1.0
# Install this file as /etc/tacplus_nss.conf
# Edit /etc/nsswitch.conf to add tacplus to the passwd lookup, similar to this
# where tacplus precede compat (or files), and depending on local policy can
# follow or precede ldap, nis, etc.
#    passwd: tacplus compat 
# The server keyword should follow the secret keyword, and may be
# given fewer times than the server keyword, if all servers have the same
# shared secret.
# is matched up with first secret line, etc.  You can use any of the
# following orders, or most other orders you can think of.  There must be at
# least as many secret lines as there are server lines.  This file should be
# kept as permisions 644, owned by root, since it must be readable by arbitrary
# processes, even though the secret for the TACACS+ server is present as clear
# text.
#  Servers are tried in the order listed, and once a server
#  replies, no other servers are attempted in a given process instantiation
# 
#  This configuration is similar to the libpam_tacplus configuration, but
#  is maintained as a configuration file, since nsswitch.conf doesn't
#  support passing parameters.  Parameters must start in the first
#  column, and parsing stops at the first whitespace

# if set, errors and other issues are logged with syslog
# debug=1

# The include keyword allows centralizing the tacacs+ server information
# including the IP address and shared secret
include=/etc/tacplus_servers

#  The server IP address can be optionally followed by a ':' and a port
#  number (server=1.1.1.1:49).
#secret=SECRET1
#server=1.1.1.1
#secret=SECRET2
#server=1.1.1.2

debug=0
service=shell
include=/etc/tacplus_servers
`

`[root@localhost ~]# cat  /etc/audisp/plugins.d/audisp-tacplus.conf
# This file controls the configuration of the
# tacplus accounting plugin for audisp; it should be installed
# in /etc/audisp/plugins.d/audisp-tacplus.conf

# default to enabling tacacs accounting; change to no to disnable
active = yes

# This can be used to specify an different config file than /etc/audisp/audisp-tac_plus.conf
# args =

# These parameters should normally not be changed.
active = yes # if no, accounting is disabled
direction = out
path = /usr/local/sbin/audisp-tacplus
type = always
format = string
`

`[root@localhost ~]# cat /etc/pam.d/tacacs
#%PAM-1.0
auth    sufficient /usr/local/lib/security/pam_tacplus.so include=/etc/tacplus_servers 
account sufficient /usr/local/lib/security/pam_tacplus.so include=/etc/tacplus_servers login=login protocol=ssh service=shell
session sufficient /usr/local/lib/security/pam_tacplus.so include=/etc/tacplus_servers login=login protocol=ssh service=shell
`

`[root@localhost ~]# cat /etc/pam.d/sshd
#%PAM-1.0
auth       include      tacacs
auth       required     pam_sepermit.so
auth       substack     password-auth
auth       include      postlogin
# Used with polkit to reauthorize users in remote sessions
-auth      optional     pam_reauthorize.so prepare
account    required     pam_nologin.so
account    include      password-auth
password   include      password-auth
# pam_selinux.so close should be the first session rule
session    required     pam_selinux.so close
session    required     pam_loginuid.so
# pam_selinux.so open should only be followed by sessions to be executed in the user context
session    required     pam_selinux.so open env_params
session    required     pam_namespace.so
session    optional     pam_keyinit.so force revoke
session    include      password-auth
session    include      postlogin
# Used with polkit to reauthorize users in remote sessions
-session   optional     pam_reauthorize.so prepare
`

**Comment by stemid** [comment]
Sorry but there is no work done on this repo. I will try to disable Issues. 

This repo is only published because a co-worker of mine who never uses github did all this for a client and I asked him if I could publish it on my github to save it. A way of documenting it.

If you want to fix anything I suggest you fork the repo.
